insert into COUNTRY_MASTER values(1,'+91','India');
insert into COUNTRY_MASTER values(2,'+1','USA');
insert into STATES_MASTER values(1,1,'Andhra Pradesh');
insert into STATES_MASTER values(2,1,'Karnataka');
insert into STATES_MASTER values(3,2,'New Jersy');
insert into STATES_MASTER values(4,2,'Ohio');
insert into CITIES_MASTER values(1,'Vizag',1);
insert into CITIES_MASTER values(2,'Guntur',1);
insert into CITIES_MASTER values(3,'Banglore',2);
insert into CITIES_MASTER values(4,'Mysore',2);
insert into CITIES_MASTER values(6,'Maywood',3);
insert into CITIES_MASTER values(7,'Westwood',3);
insert into CITIES_MASTER values(8,'Oakwood',4);
insert into CITIES_MASTER values(9,'Cuyahoga County',4);